# Comprehensive data exploration questions for UM_C19_2021.csv (University of Michigan COVID-19 Testing Data)

print("=== RECOMMENDED DATA EXPLORATION QUESTIONS ===")
print("\nBased on your University of Michigan COVID-19 testing dataset (August 2020-August 2021),")
print("here are key questions to consider for your initial analysis:\n")

print("1. TEMPORAL PATTERNS & TRENDS:")
print("   - How did the positivity rate change over the academic year?")
print("   - Were there any notable peaks in positive cases? When and why might they have occurred?")
print("   - How did testing volume fluctuate throughout the year?")
print("   - Were there differences in testing patterns between academic semesters/quarters?")
print("   - Did the ratio of positive to negative tests change significantly month-to-month?")
print("   - Were weekends and holidays associated with different testing patterns or positivity rates?\n")

print("2. DEMOGRAPHIC COMPARISONS (STUDENTS VS FACULTY/STAFF):")
print("   - What was the overall positivity rate difference between students and faculty/staff?")
print("   - Did one group consistently have higher positivity rates than the other?")
print("   - How did testing volumes compare between students and faculty/staff?")
print("   - Did students show more volatility in case numbers than faculty/staff?")
print("   - Were there any notable events where one group had a sudden increase in positive tests?\n")

print("3. RESIDENCE-BASED ANALYSIS:")
print("   - Did residential students have different positivity rates compared to non-residential students?")
print("   - How did on-campus living affect the spread of COVID-19?")
print("   - Were there specific periods where residential cases spiked?")
print("   - Did testing volumes differ significantly between residential and non-residential groups?")
print("   - How did the ratio of tests per person compare between different residence types?\n")

print("4. RISK ASSESSMENT & PUBLIC HEALTH IMPLICATIONS:")
print("   - What percentage of the university population appears to have been tested regularly?")
print("   - How effective were the university's testing protocols in detecting cases?")
print("   - Were there periods when testing capacity may have been insufficient?")
print("   - What trends might have informed university decisions about campus operations?")
print("   - How did the university's positivity rates compare to local community rates (would require external data)?\n")

print("5. COMPARATIVE ANALYSIS:")
print("   - How do weekly testing patterns compare across different months?")
print("   - Which demographic/residence group contributed most to total positive cases?")
print("   - Were there any groups that showed consistently lower/higher positivity rates?")
print("   - How did the testing strategy evolve for different groups throughout the year?")
print("   - What was the relative contribution of each group to the overall testing volume?\n")

print("6. DATA QUALITY & METHODOLOGY CONSIDERATIONS:")
print("   - Were testing frequencies consistent across different groups?")
print("   - Is there evidence of changes in testing strategies throughout the year?")
print("   - Were there any days with unusually high or low testing volumes that might warrant investigation?")
print("   - Are there any anomalies in the data that should be verified?\n")

print("7. PUBLIC POLICY & INTERVENTION ANALYSIS:")
print("   - Can you correlate any spikes in cases with specific university events or policy changes?")
print("   - How did testing rates change in response to potential policy shifts?")
print("   - Were there periods when testing appeared to increase proactively?")
print("   - What does the data suggest about the effectiveness of different testing strategies?\n")

print("These questions will help you systematically explore the dataset and uncover meaningful patterns")
print("related to COVID-19 spread, testing effectiveness, and potential risk factors within the")
print("university community over this one-year period.")